/**
 * AUTO-SYNCED — DO NOT EDIT THIS FILE DIRECTLY.
 * Source of truth: backend/src/services/reconciliation/segmentEngine.ts
 * Regenerated by scripts/sync-segment-engine.js (runs automatically as
 * `functions`'s `prebuild` step — see functions/package.json).
 */
/**
 * segmentEngine
 *
 * Single source of truth for turning a Daily Report's shift times + scan punches
 * into a reconciliation status (MATCHED / CONFLICTED / MISSING_SCAN / ...).
 *
 * This module is framework-free on purpose (no Firestore, no Express) so it can
 * be shared between the Express backend (`ReconciliationService`) and the Firebase
 * Cloud Function (`functions/src/index.ts`) without either one depending on the
 * other's package. `functions/` gets its copy via `scripts/sync-segment-engine.js`
 * (run as a `prebuild` step) — this file is the ONLY place to hand-edit the logic.
 *
 * Layout:
 *  - buildSegmentsFromShiftTimes: turns the fixed 4-key shiftTimes (day/otMorning/
 *    otNoon/otEvening) into a generic Segment[]. Future formats (e.g. an arbitrary
 *    list of job blocks) get their own `buildSegmentsFrom...` function that
 *    produces the same Segment[] shape — matchSegmentsToPunches does not need to
 *    change to support them.
 *  - matchSegmentsToPunches: pairs scan punches to an arbitrary-length Segment[].
 *    Works with any number of segments; the OT-specific bypass/penalty rules only
 *    fire for segments literally typed 'otMorning'/'otEvening' and are a no-op for
 *    any other segment type.
 */

// NOTE: this file is copied verbatim into functions/src/ by
// scripts/sync-segment-engine.js, so it must not import from anywhere outside
// itself (relative import depth differs between the two locations). The two
// status/source unions below are intentionally a self-contained mirror of
// backend/src/models/ReconciliationRecord.ts's ReconciliationStatus /
// ApprovalSource — keep them in sync if a new status is ever added there.
export type ReconciliationStatus =
  | 'PENDING'
  | 'MATCHED'
  | 'CONFLICTED'
  | 'MISSING_SCAN'
  | 'MISSING_DAILY'
  | 'ABSENT'
  | 'LEAVE'
  | 'PENDING_LEAVE_REVIEW'
  | 'HOLIDAY'
  | 'UNREGISTERED_EMPLOYEE';

export type ApprovalSource = 'daily_report' | 'scan_data' | 'manual';

export interface Segment {
  start: number; // minutes from midnight
  end: number;
  type: string;
}

export interface ClassifyResult {
  status: ReconciliationStatus;
  suggestedHours?: number;
  note?: string | null;
  lateMinutes?: number;
  earlyLeaveMinutes?: number;
  isLate?: boolean;
  isEarlyLeave?: boolean;
  approvedNormalHours?: number;
  approvedOtMorning?: number;
  approvedOtNoon?: number;
  approvedOtEvening?: number;
  totalApprovedHours?: number;
  approvalSource?: ApprovalSource;
}

/**
 * งานย่อยหนึ่งงานในวันนั้น — After-Sale เขียน field นี้เพิ่ม (2026-07) เพื่อรองรับ
 * "พนักงาน 1 คนทำหลายงานในวันเดียว โดยเวลาไม่ตรง pattern เช้า/บ่ายเดิม"
 * key ของ map = `${taskId}_${subtaskId}` (ดู DailyEmployeeTimesheets.jobSegments จริง)
 *
 * ⚠️ ยืนยันกับทีม After-Sale แล้ว (2026-07-27): field เดิมที่ระดับบนสุด
 * (shiftTimes.day, photos.laborByShift.regular ฯลฯ) เป็นแค่ "ของสรุปแบบตัดทอน
 * ให้ไม่พังไปกว่าเดิม" ระหว่างรอฝั่ง Labor รองรับ jobSegments เต็มรูปแบบ —
 * ไม่ได้ตั้งใจให้ถูกต้อง 100% (มีรูปหายจริงตอนบีบกลับเป็น 4 slot เดิม เพราะ
 * 2 งาน x 4 รูป = 8 รูปจริง ยัดลง 4 slot แบบไม่มีอะไรหายไม่ได้ในหลักการ)
 * → jobSegments คือ source of truth ที่สมบูรณ์ ควรใช้แทน field เดิมเมื่อมีค่า
 */
export interface JobSegmentEntry {
  hours?: { normal?: number; otMorning?: number; otNoon?: number; otEvening?: number };
  location?: string;
  // รูปความคืบหน้างานระหว่างทำงาน (progress photos) — ไม่ผูกกับเวลาเข้า/ออกงาน
  // เหมือน photos.laborByShift เดิม ห้ามตีความเป็น photoIn/photoOut
  photos?: { regular?: string[] };
  shiftTimes?: { day?: string; otMorning?: string; otNoon?: string; otEvening?: string };
  shifts?: { normal?: boolean; otMorning?: boolean; otNoon?: boolean; otEvening?: boolean };
  sourceReport?: string;
  subtaskId?: string;
  subtaskName?: string;
  taskId?: string;
  taskName?: string;
  lastUpdated?: string;
}

export interface JobSegment extends Segment {
  jobKey: string;
  taskId?: string;
  taskName?: string;
  subtaskId?: string;
  subtaskName?: string;
  location?: string;
  progressPhotos?: string[];
}

export interface ClassifyBySegmentsParams {
  shiftTimes?: { day?: string; otMorning?: string; otNoon?: string; otEvening?: string };
  // ถ้ามีค่า (ไม่ว่างเปล่า) จะใช้แทน shiftTimes ในการสร้าง segment ตัดสิน MATCHED/CONFLICTED
  jobSegments?: Record<string, JobSegmentEntry>;
  scanPunches: string[];
  timesheetNormalHours?: number;
  timesheetOtMorning?: number;
  timesheetOtNoon?: number;
  timesheetOtEvening?: number;
  dailyReportHours?: number;
  isHoliday?: boolean;
  isLeave?: boolean;
  leaveHours?: number;
}

export interface ClassifyByPunchCoverageParams {
  dailyReportPunches: string[];
  scanPunches: string[];
  timesheetNormalHours?: number;
  timesheetOtMorning?: number;
  timesheetOtNoon?: number;
  timesheetOtEvening?: number;
  dailyReportHours?: number;
  isHoliday?: boolean;
  isLeave?: boolean;
  leaveHours?: number;
}

// ---------------------------------------------------------------------------
// Time helpers
// ---------------------------------------------------------------------------

/** แปลง HH:mm เป็นจำนวนนาทีจากเที่ยงคืน */
export function punchToMinutes(punch: string): number {
  const [h, m] = punch.split(':').map(Number);
  return (h || 0) * 60 + (m || 0);
}

export function parseTimeRange(timeStr?: string): { start: number; end: number } | null {
  if (!timeStr) return null;
  const parts = timeStr.split('-').map((s) => s.trim());
  if (parts.length !== 2) return null;
  return { start: punchToMinutes(parts[0]), end: punchToMinutes(parts[1]) };
}

function formatTime(mins: number): string {
  const h = Math.floor(mins / 60).toString().padStart(2, '0');
  const m = (mins % 60).toString().padStart(2, '0');
  return `${h}:${m}`;
}

// ---------------------------------------------------------------------------
// Segment builder — fixed 4-key shiftTimes (Daily Report's current format)
// ---------------------------------------------------------------------------

/**
 * ใช้ shiftTimes เป็น source of truth ในการสร้างช่วงเวลาที่ควรจะมีการสแกน
 * คืน null ถ้าไม่มี shiftTimes.day (แปลว่า Daily Report ไม่มีข้อมูลช่วงเวลาทำงาน)
 *
 * ⚠️ hasOtNoon ต้องมาจาก shiftTimes.otNoon เท่านั้น ห้ามผสมค่าที่คำนวณจาก scan
 * (timesheetOtNoon ฯลฯ) เพราะ segment ต้องสร้างจาก daily report เท่านั้น — ดู
 * docs/work-hour-monitoring-logic.md section 11, Bug #3
 */
export function buildSegmentsFromShiftTimes(shiftTimes?: {
  day?: string;
  otMorning?: string;
  otNoon?: string;
  otEvening?: string;
}): Segment[] | null {
  const dayShift = parseTimeRange(shiftTimes?.day);
  const otMorning = parseTimeRange(shiftTimes?.otMorning);
  const otNoon = parseTimeRange(shiftTimes?.otNoon);
  const otEvening = parseTimeRange(shiftTimes?.otEvening);

  if (!dayShift) {
    // ไม่มีเวลาทำงานปกติ (day) เลย — เช่นงานย่อยหนึ่งใน jobSegments ที่ทำ OT ล้วนๆ
    // ไม่มีชั่วโมงปกติในงานนั้น ยังต้องสร้าง segment ให้ OT ที่ประกาศไว้ ไม่ทิ้งไปเงียบๆ
    // (ไม่งั้นสแกนของ OT ช่วงนั้นจะกลายเป็น "สแกนเกินที่ไม่ตรงช่วงเวลาใด" แทนที่จะถูกจับคู่)
    if (!otMorning && !otNoon && !otEvening) return null;
    const otOnlySegments: Segment[] = [];
    if (otMorning) otOnlySegments.push({ start: otMorning.start, end: otMorning.end, type: 'otMorning' });
    if (otNoon) otOnlySegments.push({ start: otNoon.start, end: otNoon.end, type: 'otNoon' });
    if (otEvening) otOnlySegments.push({ start: otEvening.start, end: otEvening.end, type: 'otEvening' });
    return otOnlySegments;
  }

  const segments: Segment[] = [];

  if (otMorning) {
    segments.push({ start: otMorning.start, end: otMorning.end, type: 'otMorning' });
  }

  const hasOtNoon = !!otNoon;
  const hasOtEveningConnected = !!otEvening && otEvening.start === dayShift.end;

  if (hasOtNoon) {
    segments.push({ start: dayShift.start, end: dayShift.end, type: 'normal' });
  } else if (dayShift.end <= 12 * 60) {
    segments.push({ start: dayShift.start, end: dayShift.end, type: 'morning' });
  } else if (dayShift.start >= 13 * 60) {
    if (hasOtEveningConnected) {
      segments.push({ start: dayShift.start, end: otEvening!.end, type: 'combined_afternoon_evening' });
    } else {
      segments.push({ start: dayShift.start, end: dayShift.end, type: 'afternoon' });
    }
  } else {
    segments.push({ start: dayShift.start, end: 12 * 60, type: 'morning' });
    if (hasOtEveningConnected) {
      segments.push({ start: 13 * 60, end: otEvening!.end, type: 'combined_afternoon_evening' });
    } else {
      segments.push({ start: 13 * 60, end: dayShift.end, type: 'afternoon' });
    }
  }

  if (otEvening && !(hasOtEveningConnected && !hasOtNoon)) {
    segments.push({ start: otEvening.start, end: otEvening.end, type: 'otEvening' });
  }

  return segments;
}

/**
 * แปลง jobSegments (N งานย่อยต่อวัน) เป็น Segment[] เดียวกัน — เรียกใช้
 * buildSegmentsFromShiftTimes ซ้ำต่อ 1 งาน (ตัวมันเองต่องานยังเป็น shiftTimes
 * แบบ 4-key เดิม แค่ scope แคบลงมาระดับ "งาน" แทน "วัน") แล้วต่อผลของทุกงาน
 * เรียงตามเวลาเริ่มให้ matchSegmentsToPunches ใช้ต่อได้ทันที (ตัว matcher เอง
 * ไม่ต้องแก้อะไรเลย — นี่คือประโยชน์ของการแยก builder/matcher ไว้ตั้งแต่ Track A)
 */
export function buildSegmentsFromJobSegments(
  jobSegments: Record<string, JobSegmentEntry> | undefined
): JobSegment[] {
  if (!jobSegments) return [];

  const result: JobSegment[] = [];
  for (const [jobKey, job] of Object.entries(jobSegments)) {
    const jobBaseSegments = buildSegmentsFromShiftTimes(job.shiftTimes);
    if (!jobBaseSegments) continue;
    for (const seg of jobBaseSegments) {
      result.push({
        ...seg,
        jobKey,
        taskId: job.taskId,
        taskName: job.taskName,
        subtaskId: job.subtaskId,
        subtaskName: job.subtaskName,
        location: job.location,
        progressPhotos: job.photos?.regular,
      });
    }
  }

  return result.sort((a, b) => a.start - b.start);
}

/**
 * รวม segment ที่ต่อกันพอดี (end ของอันก่อน === start ของอันถัดไป) เป็นก้อนเดียว
 * — ใช้ตอนมี jobSegments หลายงานในวันเดียว เพื่อไม่ให้จุดที่ "สลับงาน" (เช่น งาน A
 * จบ 10:00 งาน B เริ่ม 10:00 พอดี) ถูกตีความว่าเป็นจุดที่ต้องมีสแกนนิ้ว — คนงานสลับ
 * งานระหว่างวันโดยไม่ได้ออกจากไซต์ เครื่องสแกนนิ้วจับได้แค่เข้า-ออกไซต์จริงเท่านั้น
 *
 * รวมแล้วช่องว่างที่เหลืออยู่ (เช่น พักเที่ยง หรือช่วงที่ไม่มีงานระบุเลย) จะยังเป็น
 * ขอบเขตที่ต้องมีสแกนอยู่เหมือนเดิม — ฟังก์ชันนี้ลบแค่ "รอยต่อปลอม" ระหว่างงานที่ทำ
 * ต่อเนื่องกันจริงๆ ไม่ได้ลบข้อกำหนดการสแกนช่วงพักที่มีอยู่แล้ว
 */
export function mergeContiguousSegments(segments: Segment[]): Segment[] {
  if (segments.length === 0) return [];
  const sorted = [...segments].sort((a, b) => a.start - b.start);
  const merged: Segment[] = [{ ...sorted[0] }];
  for (let i = 1; i < sorted.length; i++) {
    const last = merged[merged.length - 1];
    const seg = sorted[i];
    if (seg.start === last.end) {
      last.end = seg.end;
    } else {
      merged.push({ ...seg });
    }
  }
  return merged;
}

// ---------------------------------------------------------------------------
// Punch matcher — works with any Segment[] (any length, any `type` labels)
// ---------------------------------------------------------------------------

export interface SegmentMatch {
  segment: Segment;
  matchedInMinutes: number | null;
  matchedOutMinutes: number | null;
  lateMinutes: number;
  earlyLeaveMinutes: number;
  conflicted: boolean;
  conflictReason?: string;
}

export interface SegmentMatchOutcome {
  perSegment: SegmentMatch[];
  isConflicted: boolean;
  conflictNote: string;
  totalLateMinutes: number;
  totalEarlyLeaveMinutes: number;
  penaltyOtMorning: number;
  penaltyOtEvening: number;
  // สแกนที่เหลือหลังจับคู่ทุก segment แล้ว ไม่ได้ถูกยอมรับเป็น IN/OUT ของ segment ไหนเลย
  // (นาทีจากเที่ยงคืน) — สัญญาณว่าอาจมีเวลาทำงานจริงที่ยังไม่ถูกบันทึกใน Daily Report
  extraPunches: number[];
}

/**
 * จับคู่ scanPunches กับ segments ทีละตัว (เรียงตามลำดับที่ส่งมาใน `segments`).
 * แต่ละ punch ถูกใช้ได้ครั้งเดียว (usedPunches) ยกเว้น punch ที่ตรงกับรอยต่อพอดี
 * ระหว่าง 2 segments ติดกัน (isBoundaryShared) ซึ่งใช้เป็นทั้ง OUT ของตัวก่อน
 * และ IN ของตัวถัดไปได้
 *
 * หมายเหตุ: `segments` ต้องเรียงจากเวลาเริ่มน้อยไปมากอยู่แล้วก่อนเรียกฟังก์ชันนี้
 * (buildSegmentsFromShiftTimes คืนมาเรียงอยู่แล้ว — builder อื่นในอนาคตต้อง sort เอง)
 */
export function matchSegmentsToPunches(segments: Segment[], scanPunches: string[]): SegmentMatchOutcome {
  const sortedScans = scanPunches.map((p) => punchToMinutes(p)).sort((a, b) => a - b);
  const otMorningSeg = segments.find((s) => s.type === 'otMorning') ?? null;

  let isConflicted = false;
  let totalLateMinutes = 0;
  let totalEarlyLeaveMinutes = 0;
  let penaltyOtMorning = 0;
  let penaltyOtEvening = 0;
  const conflictNotes: string[] = [];
  const usedPunches = new Set<number>();
  const perSegment: SegmentMatch[] = [];

  for (let segIndex = 0; segIndex < segments.length; segIndex++) {
    const seg = segments[segIndex];
    const nextSeg = segments[segIndex + 1];
    const available = sortedScans.filter((t) => !usedPunches.has(t));

    let closestIn = -1;
    let minInDiff = Infinity;
    for (const t of available) {
      if (t > seg.end) continue;
      const diff = Math.abs(t - seg.start);
      if (diff < minInDiff) {
        minInDiff = diff;
        closestIn = t;
      } else if (diff === minInDiff && t < closestIn) {
        closestIn = t;
      }
    }

    // ถ้า closestIn ไม่ผ่าน threshold (>90 นาทีจาก start) ถือว่ายังไม่ใช่ IN ที่ใช้ได้จริง
    // ต้องปล่อยกลับเข้า pool ก่อนหา OUT ไม่งั้น scan ตัวเดียวที่เหลือ (ซึ่งจริงๆคือ OUT ของ
    // segment นี้) จะถูก "จอง" ไว้เป็น IN ที่ไม่ผ่านไปแล้ว เหลือ pool ว่างให้หา OUT ไม่ได้เลย
    // (บั๊กเดิม: segment ที่ขาด IN แต่มี OUT ตัวเดียวจะรายงานว่าขาดทั้ง IN และเจอ scan เกิน
    // ที่ไม่ตรงช่วงเวลาใด ทั้งที่ scan ตัวนั้นคือ OUT ของ segment นี้เอง)
    const effectiveIn = closestIn !== -1 && minInDiff <= 90 ? closestIn : -1;

    let closestOut = -1;
    let minOutDiff = Infinity;
    for (const t of available) {
      if (t <= effectiveIn) continue;
      const diff = Math.abs(t - seg.end);
      if (diff < minOutDiff) {
        minOutDiff = diff;
        closestOut = t;
      } else if (diff === minOutDiff && t > closestOut) {
        closestOut = t;
      }
    }

    if (effectiveIn !== -1) usedPunches.add(effectiveIn);
    // Allow boundary-shared punches to be reused as IN of the next segment
    if (closestOut !== -1) {
      const isBoundaryShared = nextSeg && seg.end === nextSeg.start;
      if (!isBoundaryShared) {
        usedPunches.add(closestOut);
      }
    }

    let late = 0;
    let early = 0;

    // ── Transition scan bypass rules (OT เช้า ↔ กะปกติ) ──
    const isMorningTransition = seg.start === 480 && !!otMorningSeg; // กะเช้าปกติที่ทำ OT ต่อเนื่อง
    const isOtMorningTransition = seg.type === 'otMorning' && !!nextSeg && seg.end === nextSeg.start; // กะ OT เช้าที่ทำเชื่อมต่อกะปกติ

    if (closestIn === -1 || minInDiff > 90) {
      const prevHasIn =
        isMorningTransition &&
        !!otMorningSeg &&
        sortedScans.some((t) => t <= 480 + 90 && t >= otMorningSeg.start - 90);
      if (!isMorningTransition || !prevHasIn) {
        isConflicted = true;
        const reason = `ไม่พบสแกน IN สำหรับ segment ${formatTime(seg.start)}–${formatTime(seg.end)}`;
        conflictNotes.push(reason);
        perSegment.push({
          segment: seg,
          matchedInMinutes: null,
          matchedOutMinutes: closestOut !== -1 ? closestOut : null,
          lateMinutes: 0,
          earlyLeaveMinutes: 0,
          conflicted: true,
          conflictReason: reason,
        });
        continue;
      }
    } else {
      const rawLate = closestIn - seg.start;
      if (isMorningTransition && rawLate <= 5) {
        late = 0;
      } else {
        late = Math.max(0, rawLate);
      }
    }

    if (closestOut === -1 || minOutDiff > 90) {
      const nextHasOut =
        isOtMorningTransition && !!nextSeg && sortedScans.some((t) => t >= seg.end - 90 && t <= nextSeg.end + 90);
      if (!isOtMorningTransition || !nextHasOut) {
        isConflicted = true;
        const reason = `ไม่พบสแกน OUT สำหรับ segment ${formatTime(seg.start)}–${formatTime(seg.end)}`;
        conflictNotes.push(reason);
        perSegment.push({
          segment: seg,
          matchedInMinutes: closestIn !== -1 ? closestIn : null,
          matchedOutMinutes: null,
          lateMinutes: late,
          earlyLeaveMinutes: 0,
          conflicted: true,
          conflictReason: reason,
        });
        continue;
      }
    } else {
      early = Math.max(0, seg.end - closestOut);
    }

    let segConflicted = false;
    let segReason: string | undefined;

    if (late > 30) {
      isConflicted = true;
      segConflicted = true;
      segReason = `สแกนเข้าสายเกิน 30 นาทีในรอบ ${formatTime(seg.start)} (${late} นาที)`;
      conflictNotes.push(segReason);
    }
    if (early > 30) {
      isConflicted = true;
      segConflicted = true;
      segReason = `สแกนออกก่อนเกิน 30 นาทีในรอบ ${formatTime(seg.end)} (${early} นาที)`;
      conflictNotes.push(segReason);
    }

    if (late > 0) {
      totalLateMinutes += late;
      if (seg.type === 'otMorning' || (otMorningSeg && seg.start === otMorningSeg.start)) {
        penaltyOtMorning += late;
      }
    }
    if (early > 0) {
      totalEarlyLeaveMinutes += early;
      if (seg.type === 'otEvening' || seg.type === 'combined_afternoon_evening') {
        penaltyOtEvening += early;
      }
    }

    perSegment.push({
      segment: seg,
      matchedInMinutes: closestIn !== -1 ? closestIn : null,
      matchedOutMinutes: closestOut !== -1 ? closestOut : null,
      lateMinutes: late,
      earlyLeaveMinutes: early,
      conflicted: segConflicted,
      conflictReason: segReason,
    });
  }

  const consumedMinutes = new Set<number>();
  perSegment.forEach((m) => {
    if (m.matchedInMinutes != null) consumedMinutes.add(m.matchedInMinutes);
    if (m.matchedOutMinutes != null) consumedMinutes.add(m.matchedOutMinutes);
  });
  const extraPunches = sortedScans.filter((t) => !consumedMinutes.has(t));

  return {
    perSegment,
    isConflicted,
    conflictNote: conflictNotes.join(', '),
    totalLateMinutes,
    totalEarlyLeaveMinutes,
    penaltyOtMorning,
    penaltyOtEvening,
    extraPunches,
  };
}

// ---------------------------------------------------------------------------
// Base cases shared by both classify entry points
// ---------------------------------------------------------------------------

interface BaseCaseParams {
  scanCount: number;
  dailyWorkExists: boolean;
  dailyReportHours?: number;
  isHoliday?: boolean;
  isLeave?: boolean;
  leaveHours?: number;
  firstScanPunch?: string;
}

function classifyBaseCases(params: BaseCaseParams): ClassifyResult | null {
  const { scanCount, dailyWorkExists, isHoliday, isLeave, leaveHours, dailyReportHours, firstScanPunch } = params;

  const isFullDayLeave = isLeave === true && (leaveHours ?? 0) >= 8;
  const isPartialLeave = isLeave === true && (leaveHours ?? 0) > 0 && (leaveHours ?? 0) < 8;
  const noWorkHours = !dailyReportHours || dailyReportHours === 0;
  const dailyExists = dailyWorkExists || isPartialLeave;

  if (isFullDayLeave && noWorkHours) {
    return { status: 'LEAVE' };
  }

  if (isHoliday && noWorkHours) {
    if (scanCount > 0) {
      return { status: 'CONFLICTED', suggestedHours: 0, note: `วันหยุดแต่พบข้อมูลการสแกนนิ้ว (${scanCount} ครั้ง)` };
    }
    return { status: 'HOLIDAY' };
  }

  if (isPartialLeave && !dailyWorkExists) {
    if (scanCount > 0) {
      return {
        status: 'CONFLICTED',
        suggestedHours: 0,
        note: `แจ้งลา ${leaveHours} ชม. แต่ใน Daily Report ไม่มีการลงเวลาทำงานส่วนที่เหลือ และพบข้อมูลสแกนนิ้ว (${scanCount} ครั้ง)`,
      };
    }
    return {
      status: 'MISSING_DAILY',
      suggestedHours: 0,
      note: `แจ้งลา ${leaveHours} ชม. แต่ใน Daily Report ไม่มีการลงเวลาทำงานส่วนที่เหลือ`,
    };
  }

  if (!dailyExists && scanCount === 0) return { status: 'ABSENT' };
  if (!dailyExists && scanCount > 0) return { status: 'MISSING_DAILY' };

  if (dailyExists && scanCount === 0) {
    return { status: 'MISSING_SCAN', suggestedHours: 0, note: 'ไม่พบข้อมูลการสแกนนิ้ว' };
  }

  if (dailyExists && scanCount === 1) {
    return {
      status: 'CONFLICTED',
      suggestedHours: 0,
      note: `ข้อมูลสแกนนิ้วไม่เพียงพอ (พบเพียงครั้งเดียว: ${firstScanPunch}) — Admin ต้องเติมเวลาที่ขาด`,
    };
  }

  return null; // no base case matched — proceed to segment/coverage check
}

// ---------------------------------------------------------------------------
// [PRIMARY] classifyBySegments
// ---------------------------------------------------------------------------

export function classifyBySegments(params: ClassifyBySegmentsParams): ClassifyResult {
  const {
    shiftTimes,
    jobSegments,
    scanPunches,
    timesheetNormalHours,
    timesheetOtMorning,
    timesheetOtNoon,
    timesheetOtEvening,
    dailyReportHours,
    isHoliday,
    isLeave,
    leaveHours,
  } = params;

  const hasJobSegments = !!jobSegments && Object.keys(jobSegments).length > 0;
  const scanCount = (scanPunches || []).length;
  const dailyWorkExists =
    hasJobSegments || !!shiftTimes?.day || (dailyReportHours !== undefined && dailyReportHours > 0);

  const base = classifyBaseCases({
    scanCount,
    dailyWorkExists,
    dailyReportHours,
    isHoliday,
    isLeave,
    leaveHours,
    firstScanPunch: scanPunches?.[0],
  });
  if (base) return base;

  // jobSegments (N งานย่อยต่อวัน) คือ source of truth เมื่อมีค่า — ดู doc comment
  // ของ JobSegmentEntry ด้านบน ยืนยันกับ After-Sale แล้วว่า shiftTimes เดิม
  // เป็นแค่ของสรุปแบบตัดทอน ไม่ใช้ตัดสิน MATCHED/CONFLICTED อีกต่อไปเมื่อมี jobSegments
  let segments: Segment[] | null;
  if (hasJobSegments) {
    const rawJobSegments = buildSegmentsFromJobSegments(jobSegments);
    if (rawJobSegments.length === 0) {
      return { status: 'MISSING_DAILY', note: 'Daily Report ไม่มีข้อมูลช่วงเวลาทำงาน (Shift Times)' };
    }
    // งานที่ต่อกันพอดี (สลับงานโดยไม่ออกจากไซต์) ต้องรวมเป็น segment เดียวก่อนจับคู่
    // สแกน ไม่งั้นตัว matcher จะไปคาดหวังสแกนนิ้วตรงจุดสลับงานทั้งที่ไม่มีจริง
    segments = mergeContiguousSegments(rawJobSegments);
  } else {
    if (!shiftTimes || !shiftTimes.day) {
      return { status: 'MISSING_DAILY', note: 'Daily Report ไม่มีข้อมูลช่วงเวลาทำงาน (Shift Times)' };
    }
    segments = buildSegmentsFromShiftTimes(shiftTimes);
    if (!segments) {
      return { status: 'MISSING_DAILY', note: 'Daily Report ไม่มีข้อมูลช่วงเวลาทำงาน (Shift Times)' };
    }
  }

  const outcome = matchSegmentsToPunches(segments, scanPunches);

  // สแกนที่เหลือไม่ตรงกับ segment ไหนเลย (เช่น สแกนหลังเวลาที่ Daily Report บอกว่าเลิกงาน) —
  // เป็นสัญญาณว่ามีเวลาทำงานที่ยังไม่ถูกบันทึกไว้ ต้องบังคับ CONFLICTED เสมอ ไม่ว่า segment
  // ที่ประกาศไว้จะตรงครบแค่ไหนก็ตาม ไม่งั้นสแกนส่วนเกินนี้จะถูกมองข้ามไปเงียบๆ (พบจากรีวิวจริงกับผู้ใช้)
  const extraNote =
    outcome.extraPunches.length > 0
      ? `พบสแกน ${outcome.extraPunches.map(formatTime).join(', ')} ที่ไม่ตรงช่วงเวลาใด`
      : null;

  // Daily Report ที่ประกาศช่วงเวลาทำงาน "ปกติ" (ไม่นับ otMorning/otEvening ซึ่งเป็นส่วนเสริม)
  // สั้นกว่า 1 วันมาตรฐาน (08:00-17:00) โดยไม่มีใบลา/วันหยุดมารองรับส่วนที่ขาด — ต้องบังคับ
  // CONFLICTED เสมอเช่นกัน เพราะไม่รู้ว่าลืมลงข้อมูล (report/สแกน) หรือลาแล้วลืมลงใบลา หรือ
  // ตั้งใจให้สั้นจริงๆ ปล่อยให้ admin เป็นคนตัดสินใจแทนที่จะปล่อยผ่านเป็น MATCHED เงียบๆ
  const NORMAL_DAY_START = 8 * 60; // 08:00
  const NORMAL_DAY_END = 17 * 60; // 17:00
  const coverageSegments = segments.filter((s) => s.type !== 'otMorning' && s.type !== 'otEvening');
  const coverageStart = coverageSegments.length > 0 ? Math.min(...coverageSegments.map((s) => s.start)) : null;
  const coverageEnd = coverageSegments.length > 0 ? Math.max(...coverageSegments.map((s) => s.end)) : null;
  const isShortDay =
    !isLeave &&
    !isHoliday &&
    coverageStart !== null &&
    coverageEnd !== null &&
    (coverageStart > NORMAL_DAY_START || coverageEnd < NORMAL_DAY_END);
  const shortDayNote = isShortDay
    ? `Daily Report ลงเวลาแค่ ${formatTime(coverageStart!)}-${formatTime(coverageEnd!)} ไม่ครบวันทำงานมาตรฐาน (08:00-17:00) และไม่มีใบลา/วันหยุดรองรับ`
    : null;

  if (outcome.isConflicted || extraNote || shortDayNote) {
    return {
      status: 'CONFLICTED',
      suggestedHours: dailyReportHours,
      approvedNormalHours: timesheetNormalHours,
      approvedOtMorning: timesheetOtMorning,
      approvedOtNoon: timesheetOtNoon,
      approvedOtEvening: timesheetOtEvening,
      totalApprovedHours:
        (timesheetNormalHours || 0) + (timesheetOtMorning || 0) + (timesheetOtNoon || 0) + (timesheetOtEvening || 0),
      approvalSource: 'daily_report',
      lateMinutes: outcome.totalLateMinutes,
      earlyLeaveMinutes: outcome.totalEarlyLeaveMinutes,
      isLate: outcome.totalLateMinutes > 0,
      isEarlyLeave: outcome.totalEarlyLeaveMinutes > 0,
      note: [outcome.conflictNote, extraNote, shortDayNote].filter(Boolean).join(' · ') || null,
    };
  }

  let approvedNormal = timesheetNormalHours ?? dailyReportHours ?? 0;
  let approvedMorning = timesheetOtMorning ?? 0;
  let approvedNoon = timesheetOtNoon ?? 0;
  let approvedEvening = timesheetOtEvening ?? 0;
  let autoNote = '';

  if (outcome.penaltyOtMorning > 0 && approvedMorning > 0) {
    const penaltyMins = Math.ceil(outcome.penaltyOtMorning / 30) * 30;
    approvedMorning = Math.max(0, approvedMorning - penaltyMins / 60);
    autoNote += `สายช่วง OT เช้า ${outcome.penaltyOtMorning} นาที (หัก ${penaltyMins} นาที) `;
  }

  if (outcome.penaltyOtEvening > 0 && approvedEvening > 0) {
    const penaltyMins = Math.ceil(outcome.penaltyOtEvening / 30) * 30;
    approvedEvening = Math.max(0, approvedEvening - penaltyMins / 60);
    autoNote += `ออกก่อนช่วง OT เย็น ${outcome.penaltyOtEvening} นาที (หัก ${penaltyMins} นาที) `;
  }

  return {
    status: 'MATCHED',
    suggestedHours: dailyReportHours,
    approvedNormalHours: approvedNormal,
    approvedOtMorning: approvedMorning,
    approvedOtNoon: approvedNoon,
    approvedOtEvening: approvedEvening,
    totalApprovedHours: approvedNormal + approvedMorning + approvedNoon + approvedEvening,
    approvalSource: 'daily_report',
    lateMinutes: outcome.totalLateMinutes,
    earlyLeaveMinutes: outcome.totalEarlyLeaveMinutes,
    isLate: outcome.totalLateMinutes > 0,
    isEarlyLeave: outcome.totalEarlyLeaveMinutes > 0,
    note: autoNote || null,
  };
}

// ---------------------------------------------------------------------------
// [PRIMARY] classifyByPunchCoverage — legacy fallback for docs without shiftTimes
// ---------------------------------------------------------------------------

export function classifyByPunchCoverage(params: ClassifyByPunchCoverageParams): ClassifyResult {
  const {
    dailyReportPunches,
    scanPunches,
    timesheetNormalHours,
    timesheetOtMorning,
    timesheetOtNoon,
    timesheetOtEvening,
    dailyReportHours,
    isHoliday,
    isLeave,
    leaveHours,
  } = params;

  const dailyPunchesValid = Array.isArray(dailyReportPunches) && dailyReportPunches.length >= 2;
  const scanCount = (scanPunches || []).length;
  const scanValid = scanCount >= 2;
  const dailyWorkExists = dailyPunchesValid || (dailyReportHours !== undefined && dailyReportHours > 0);

  const isFullDayLeave = isLeave === true && (leaveHours ?? 0) >= 8;
  const isPartialLeave = isLeave === true && (leaveHours ?? 0) > 0 && (leaveHours ?? 0) < 8;
  const noWorkHours = !dailyReportHours || dailyReportHours === 0;
  const dailyExists = dailyWorkExists || isPartialLeave;

  if (isFullDayLeave && noWorkHours) return { status: 'LEAVE' };

  if (isHoliday && noWorkHours) {
    if (scanCount > 0) {
      return { status: 'CONFLICTED', suggestedHours: 0, note: `วันหยุดแต่พบข้อมูลการสแกนนิ้ว (${scanCount} ครั้ง)` };
    }
    return { status: 'HOLIDAY' };
  }

  if (isPartialLeave && !dailyWorkExists) {
    if (scanCount > 0) {
      return {
        status: 'CONFLICTED',
        suggestedHours: 0,
        note: `แจ้งลา ${leaveHours} ชม. แต่ใน Daily Report ไม่มีการลงเวลาทำงานส่วนที่เหลือ และพบข้อมูลสแกนนิ้ว (${scanCount} ครั้ง)`,
      };
    }
    return {
      status: 'MISSING_DAILY',
      suggestedHours: 0,
      note: `แจ้งลา ${leaveHours} ชม. แต่ใน Daily Report ไม่มีการลงเวลาทำงานส่วนที่เหลือ`,
    };
  }

  if (!dailyExists && !scanValid) return { status: 'ABSENT' };
  if (!dailyExists && scanValid) return { status: 'MISSING_DAILY' };
  if (dailyExists && !scanValid) {
    if (scanCount === 0) {
      return { status: 'MISSING_SCAN', suggestedHours: 0, note: 'ไม่พบข้อมูลการสแกนนิ้ว' };
    }
    return {
      status: 'CONFLICTED',
      suggestedHours: 0,
      note: `ข้อมูลสแกนนิ้วไม่เพียงพอ (พบเพียงครั้งเดียว: ${scanPunches[0]}) — Admin ต้องเติมเวลาที่ขาด`,
    };
  }

  if (!dailyPunchesValid) {
    return { status: 'MISSING_DAILY', note: 'Daily Report ไม่มีข้อมูลช่วงเวลาทำงาน (Shift Times)' };
  }

  const sortedReportPunches = [...dailyReportPunches].sort();
  const reportStart = punchToMinutes(sortedReportPunches[0]);
  const reportEnd = punchToMinutes(sortedReportPunches[sortedReportPunches.length - 1]);

  const sortedScan = [...(scanPunches || [])].sort();
  const scanFirstIn = punchToMinutes(sortedScan[0]);
  const scanLastOut = punchToMinutes(sortedScan[sortedScan.length - 1]);

  const lateMinutes = Math.max(0, scanFirstIn - reportStart);
  const earlyLeaveMinutes = Math.max(0, reportEnd - scanLastOut);

  const CONFLICT_THRESHOLD = 30;
  const isLateConflict = lateMinutes > CONFLICT_THRESHOLD;
  const isEarlyLeaveConflict = earlyLeaveMinutes > CONFLICT_THRESHOLD;

  if (isLateConflict || isEarlyLeaveConflict) {
    return {
      status: 'CONFLICTED',
      lateMinutes,
      earlyLeaveMinutes,
      isLate: isLateConflict,
      isEarlyLeave: isEarlyLeaveConflict,
      note: isEarlyLeaveConflict
        ? `ออกก่อนเกิน ${CONFLICT_THRESHOLD} นาที (${earlyLeaveMinutes} นาที) — ต้องตรวจสอบ Daily Report`
        : `สายเกิน ${CONFLICT_THRESHOLD} นาที (${lateMinutes} นาที) — ต้องตรวจสอบ Daily Report`,
    };
  }

  let approvedNormalHours = timesheetNormalHours ?? dailyReportHours ?? 0;
  let approvedOtMorning = timesheetOtMorning ?? 0;
  let approvedOtNoon = timesheetOtNoon ?? 0;
  let approvedOtEvening = timesheetOtEvening ?? 0;
  let autoNote = '';

  const isLateForOT = lateMinutes > 0 && (timesheetOtMorning ?? 0) > 0;
  const isEarlyLeaveFromOT = earlyLeaveMinutes > 0 && (timesheetOtEvening ?? 0) > 0;

  if (isLateForOT) {
    const penaltyMins = Math.ceil(lateMinutes / 30) * 30;
    approvedOtMorning = Math.max(0, (timesheetOtMorning ?? 0) - penaltyMins / 60);
    autoNote += `สายช่วง OT เช้า ${lateMinutes} นาที (หัก ${penaltyMins} นาที) `;
  }

  if (isEarlyLeaveFromOT) {
    const penaltyMins = Math.ceil(earlyLeaveMinutes / 30) * 30;
    approvedOtEvening = Math.max(0, (timesheetOtEvening ?? 0) - penaltyMins / 60);
    autoNote += `ออกก่อนช่วง OT เย็น ${earlyLeaveMinutes} นาที (หัก ${penaltyMins} นาที) `;
  }

  return {
    status: 'MATCHED',
    suggestedHours: dailyReportHours,
    approvedNormalHours,
    approvedOtMorning,
    approvedOtNoon,
    approvedOtEvening,
    totalApprovedHours: approvedNormalHours + approvedOtMorning + approvedOtNoon + approvedOtEvening,
    approvalSource: 'daily_report',
    lateMinutes,
    earlyLeaveMinutes,
    isLate: lateMinutes > 0,
    isEarlyLeave: earlyLeaveMinutes > 0,
    note: autoNote || null,
  };
}

// ---------------------------------------------------------------------------
// Display segments — for ReconciliationRecord.segments (UI rendering only)
// ---------------------------------------------------------------------------
//
// classifyBySegments() above merges morning+afternoon into ONE 'normal' segment
// when otNoon is present, because for MATCHED/CONFLICTED purposes there is no
// scan expected at the 12:00/13:00 boundary. The UI, however, has always shown
// that case as 3 separate boxes (เช้า / OT เที่ยง / บ่าย) — buildDisplaySegments
// preserves that exact visual behavior while still going through the shared
// matchSegmentsToPunches matcher (no separate matching logic to maintain).
// This is display-only: it does NOT feed into the MATCHED/CONFLICTED decision.

// `any[]` on purpose: leaveEntries shapes vary slightly between call sites
// (CreateReconciliationRecordInput.leaveEntries doesn't even declare timeRange
// in its type even though it's present at runtime) — this reads .timeRange
// defensively and skips anything that doesn't parse, so a loose type here is
// more honest than a strict interface no caller actually satisfies.
function isSegmentCoveredByLeave(
  leaveEntries: any[] | undefined,
  start: number,
  end: number
): boolean {
  if (!leaveEntries || leaveEntries.length === 0) return false;
  for (const entry of leaveEntries) {
    const range = parseTimeRange(entry?.timeRange);
    if (!range) continue;
    const overlapStart = Math.max(start, range.start);
    const overlapEnd = Math.min(end, range.end);
    if (overlapEnd > overlapStart) {
      const overlapDuration = overlapEnd - overlapStart;
      const segmentDuration = end - start;
      if (segmentDuration > 0 && overlapDuration >= segmentDuration * 0.8) return true;
    }
  }
  return false;
}

/**
 * เหมือน buildSegmentsFromShiftTimes แต่ "ไม่รวม" เช้า+บ่ายเป็น 1 ก้อนตอนมี OT เที่ยง
 * (ใช้แค่สำหรับแสดงผล UI — ตัดสิน MATCHED/CONFLICTED จริงใช้ buildSegmentsFromShiftTimes)
 */
export function buildDisplaySegments(
  shiftTimes?: { day?: string; otMorning?: string; otNoon?: string; otEvening?: string },
  leaveEntries?: any[]
): Segment[] {
  const dayShift = parseTimeRange(shiftTimes?.day);
  if (!dayShift) return [];

  const otMorning = parseTimeRange(shiftTimes?.otMorning);
  const otNoon = parseTimeRange(shiftTimes?.otNoon);
  const otEvening = parseTimeRange(shiftTimes?.otEvening);

  const morningEnd = Math.min(dayShift.end, 12 * 60);
  const afternoonStart = Math.max(dayShift.start, 13 * 60);
  const isMorningActive = dayShift.start < 13 * 60;
  const isAfternoonActive = dayShift.end > 12 * 60;

  const segments: Segment[] = [];
  if (otMorning) segments.push({ start: otMorning.start, end: otMorning.end, type: 'otMorning' });
  if (isMorningActive && !isSegmentCoveredByLeave(leaveEntries, dayShift.start, morningEnd)) {
    segments.push({ start: dayShift.start, end: morningEnd, type: 'morning' });
  }
  if (otNoon) segments.push({ start: otNoon.start, end: otNoon.end, type: 'otNoon' });
  if (isAfternoonActive && !isSegmentCoveredByLeave(leaveEntries, afternoonStart, dayShift.end)) {
    segments.push({ start: afternoonStart, end: dayShift.end, type: 'afternoon' });
  }
  if (otEvening) segments.push({ start: otEvening.start, end: otEvening.end, type: 'otEvening' });

  return segments.sort((a, b) => a.start - b.start);
}

export interface DailyReportPhotosShape {
  regular?: unknown;
  otMorning?: unknown;
  otNoon?: unknown;
  otEvening?: unknown;
}

function extractPhoto(groupData: unknown, which: 'in' | 'out'): string | null {
  if (!groupData) return null;
  if (Array.isArray(groupData)) {
    return which === 'in' ? (groupData[0] ?? null) : (groupData[groupData.length - 1] ?? null);
  }
  if (typeof groupData === 'object') {
    const obj = groupData as Record<string, unknown>;
    if (which in obj) return (obj[which] as string) ?? null;
    const keys = Object.keys(obj);
    const isNumericMap = keys.length > 0 && keys.every((k) => /^\d+$/.test(k));
    if (isNumericMap) {
      const sortedKeys = keys.map(Number).sort((a, b) => a - b);
      const targetKey = which === 'in' ? sortedKeys[0] : sortedKeys[sortedKeys.length - 1];
      return (obj[String(targetKey)] as string) ?? null;
    }
  }
  return null;
}

function extractRegularPhoto(regular: unknown, index: number): string | null {
  if (!regular) return null;
  if (Array.isArray(regular)) return regular[index] ?? null;
  if (typeof regular === 'object') {
    const obj = regular as Record<string, unknown>;
    return (obj[String(index)] as string) ?? null;
  }
  return null;
}

export interface SegmentSnapshot {
  type: string;
  expectedStart: number;
  expectedEnd: number;
  matchedInMinutes: number | null;
  matchedOutMinutes: number | null;
  lateMinutes: number;
  earlyLeaveMinutes: number;
  conflicted: boolean;
  conflictReason?: string;
  photoIn?: string | null;
  photoOut?: string | null;
}

/**
 * ผลลัพธ์สำเร็จรูปสำหรับ UI แสดงตาราง work-hour-monitoring — คำนวณครั้งเดียวที่ backend
 * แล้ว persist ไปกับ ReconciliationRecord.segments เพื่อไม่ให้ frontend ต้องจับคู่ punch เอง
 * (เดิม WorkHourComparisonTable.tsx ทำ matching ของตัวเองอีกรอบ — เป็น engine ที่ 3)
 */
export function buildSegmentSnapshots(
  shiftTimes: { day?: string; otMorning?: string; otNoon?: string; otEvening?: string } | undefined,
  scanPunches: string[],
  photos?: DailyReportPhotosShape,
  leaveEntries?: any[]
): SegmentSnapshot[] {
  const displaySegments = buildDisplaySegments(shiftTimes, leaveEntries);
  if (displaySegments.length === 0) return [];

  const outcome = matchSegmentsToPunches(displaySegments, scanPunches);

  return outcome.perSegment.map((m) => {
    let photoIn: string | null = null;
    let photoOut: string | null = null;

    if (m.segment.type === 'morning') {
      photoIn = extractRegularPhoto(photos?.regular, 0);
      photoOut = extractRegularPhoto(photos?.regular, 1);
    } else if (m.segment.type === 'afternoon') {
      photoIn = extractRegularPhoto(photos?.regular, 2);
      photoOut = extractRegularPhoto(photos?.regular, 3);
    } else {
      const group = (photos as Record<string, unknown> | undefined)?.[m.segment.type];
      photoIn = extractPhoto(group, 'in');
      photoOut = extractPhoto(group, 'out');
    }

    return {
      type: m.segment.type,
      expectedStart: m.segment.start,
      expectedEnd: m.segment.end,
      matchedInMinutes: m.matchedInMinutes,
      matchedOutMinutes: m.matchedOutMinutes,
      lateMinutes: m.lateMinutes,
      earlyLeaveMinutes: m.earlyLeaveMinutes,
      conflicted: m.conflicted,
      conflictReason: m.conflictReason,
      photoIn,
      photoOut,
    };
  });
}
