/**
 * ScanData Service
 * API integration สำหรับ ScanData Management
 */

import apiClient from './api/client';
import type {
  ScanDataFilter,
  DiscrepancyFilter,
  LateRecordFilter,
  ResolveDiscrepancyInput,
} from '../validation/scanDataSchema';

/**
 * ScanData Interface
 */
export interface ScanData {
  id: string;
  employeeNumber: string;
  dailyContractorId?: string;
  dailyContractorName?: string;
  projectLocationId: string;
  projectLocationName?: string;
  scanDateTime: Date;
  scanDate: Date;
  scanType:
    | 'ot_morning_in'
    | 'ot_morning_out'
    | 'regular_in'
    | 'late'
    | 'lunch_break'
    | 'regular_out'
    | 'ot_noon'
    | 'ot_evening_in'
    | 'ot_evening_out';
  scanTimeSlot: string;
  isFirstScanOfDay: boolean;
  isLastScanOfDay: boolean;
  isDuplicate: boolean;
  relatedScanId?: string;
  calculatedHours?: number;
  roundedHours?: number;
  lateMinutes?: number;
  importBatchId: string;
  importTimestamp: Date;
  hasDiscrepancy: boolean;
  notes?: string;
  rawData?: any;
}

/**
 * ScanData Discrepancy Interface
 */
export interface ScanDataDiscrepancy {
  id: string;
  dailyContractorId: string;
  dailyContractorName?: string;
  employeeNumber: string;
  projectLocationId: string;
  projectLocationName?: string;
  workDate: Date;
  discrepancyType: 'Type1' | 'Type2' | 'Type3';
  severity: 'low' | 'medium' | 'high';
  dailyReportHours?: number;
  scanDataHours?: number;
  hoursDifference?: number;
  dailyReportIds?: string[];
  scanDataIds?: string[];
  status: 'pending' | 'verified' | 'fixed' | 'ignored';
  resolutionAction?: string;
  resolutionNotes?: string;
  resolutionMethod?: 'update_dr' | 'create_dr' | 'verify' | 'ignore';
  resolutionNote?: string;
  detectedAt: Date;
  resolvedAt?: Date;
  resolvedBy?: string;
  autoGenerated: boolean;
  // Additional detail properties
  dailyReportData?: {
    startTime?: string;
    endTime?: string;
    workHours?: number;
  };
  scanDataRecords?: Array<{
    scanTime: string;
    scanType: string;
    roundedTime?: string;
  }>;
}

/**
 * Late Record Interface
 */
export interface LateRecord {
  id: string;
  dailyContractorId: string;
  dailyContractorName?: string;
  employeeNumber: string;
  projectLocationId: string;
  projectLocationName?: string;
  lateDate: Date;
  scanDataId: string;
  scanTime: Date;
  expectedTime: Date;
  lateMinutes: number;
  deductionAmount?: number;
  wagePeriodId?: string;
  includedInWageCalculation: boolean;
  notes?: string;
  createdAt: Date;
  createdBy?: string;
}

/**
 * Import Result Interface
 */
export interface ImportResult {
  success: boolean;
  importBatchId: string;
  totalRecords: number;
  successfulRecords: number;
  failedRecords: number;
  errors: Array<{
    row: number;
    employeeNumber?: string;
    error: string;
  }>;
  warnings: string[];
}

/**
 * Discrepancy Summary Interface
 */
export interface DiscrepancySummary {
  totalDiscrepancies: number;
  pendingCount: number;
  type1Count: number;
  type2Count: number;
  type3Count: number;
  highSeverityCount: number;
  recentDiscrepancies: ScanDataDiscrepancy[];
}

/**
 * Upload ScanData file (.dat หรือ Excel) และ import เข้าระบบ
 */
export async function uploadScanDataFile(
  file: File,
  projectLocationId: string,
  importNote?: string
): Promise<ImportResult> {
  const formData = new FormData();
  formData.append('file', file);
  formData.append('projectLocationId', projectLocationId);
  if (importNote) {
    formData.append('importNote', importNote);
  }

  const response = await apiClient.post<{ success: boolean; data: ImportResult }>(
    '/scan-data/import',
    formData,
    {
      headers: {
        'Content-Type': 'multipart/form-data',
      },
    }
  );
  return response.data.data;
}

export const uploadScanDataExcel = uploadScanDataFile;

/**
 * Get all scan data with filtering
 */
export async function getAllScanData(
  filter?: ScanDataFilter,
  page: number = 1,
  pageSize: number = 50
): Promise<{
  data: ScanData[];
  total: number;
  page: number;
  pageSize: number;
}> {
  const params = new URLSearchParams();
  params.append('page', String(page));
  params.append('pageSize', String(pageSize));

  if (filter) {
    if (filter.projectLocationId)
      params.append('projectLocationId', filter.projectLocationId);
    if (filter.dailyContractorId)
      params.append('dailyContractorId', filter.dailyContractorId);
    if (filter.employeeNumber) params.append('employeeNumber', filter.employeeNumber);
    if (filter.startDate)
      params.append('startDate', filter.startDate.toISOString());
    if (filter.endDate) params.append('endDate', filter.endDate.toISOString());
    if (filter.scanType) params.append('scanType', filter.scanType);
    if (filter.hasDiscrepancy !== undefined)
      params.append('hasDiscrepancy', String(filter.hasDiscrepancy));
    if (filter.importBatchId) params.append('importBatchId', filter.importBatchId);
  }

  const response = await apiClient.get<{
    success: boolean;
    data: ScanData[];
    pagination: { total: number; page: number; pageSize: number };
  }>(`/scan-data?${params.toString()}`);

  return {
    data: response.data.data,
    total: response.data.pagination.total,
    page: response.data.pagination.page,
    pageSize: response.data.pagination.pageSize,
  };
}

/**
 * Get scan data by ID
 */
export async function getScanDataById(id: string): Promise<ScanData> {
  const response = await apiClient.get<{ success: boolean; data: ScanData }>(
    `/scan-data/${id}`
  );
  return response.data.data;
}

/**
 * Delete scan data (ลบทั้ง batch)
 */
export async function deleteScanDataBatch(importBatchId: string): Promise<void> {
  await apiClient.delete(`/scan-data/batch/${importBatchId}`);
}

/**
 * Get all discrepancies with filtering
 */
export async function getAllDiscrepancies(
  filter?: DiscrepancyFilter,
  page: number = 1,
  pageSize: number = 50
): Promise<{
  data: ScanDataDiscrepancy[];
  total: number;
  page: number;
  pageSize: number;
}> {
  const params = new URLSearchParams();
  params.append('page', String(page));
  params.append('pageSize', String(pageSize));

  if (filter) {
    if (filter.projectLocationId)
      params.append('projectLocationId', filter.projectLocationId);
    if (filter.dailyContractorId)
      params.append('dailyContractorId', filter.dailyContractorId);
    if (filter.employeeNumber) params.append('employeeNumber', filter.employeeNumber);
    if (filter.startDate)
      params.append('startDate', filter.startDate.toISOString());
    if (filter.endDate) params.append('endDate', filter.endDate.toISOString());
    if (filter.discrepancyType)
      params.append('discrepancyType', filter.discrepancyType);
    if (filter.severity) params.append('severity', filter.severity);
    if (filter.status) params.append('status', filter.status);
  }

  const response = await apiClient.get<{
    success: boolean;
    data: ScanDataDiscrepancy[];
    pagination: { total: number; page: number; pageSize: number };
  }>(`/scan-data/discrepancies?${params.toString()}`);

  return {
    data: response.data.data,
    total: response.data.pagination.total,
    page: response.data.pagination.page,
    pageSize: response.data.pagination.pageSize,
  };
}

/**
 * Get discrepancy by ID
 */
export async function getDiscrepancyById(id: string): Promise<ScanDataDiscrepancy> {
  const response = await apiClient.get<{
    success: boolean;
    data: ScanDataDiscrepancy;
  }>(`/scan-data/discrepancies/${id}`);
  return response.data.data;
}

/**
 * Get discrepancy summary for dashboard
 */
export async function getDiscrepancySummary(
  projectLocationId?: string
): Promise<DiscrepancySummary> {
  const params = new URLSearchParams();
  if (projectLocationId) {
    params.append('projectLocationId', projectLocationId);
  }

  const response = await apiClient.get<{
    success: boolean;
    data: DiscrepancySummary;
  }>(`/scan-data/discrepancies/summary?${params.toString()}`);

  return response.data.data;
}

/**
 * Resolve discrepancy
 */
export async function resolveDiscrepancy(
  discrepancyId: string,
  resolutionData: {
    method: 'update_dr' | 'create_dr' | 'verify' | 'ignore';
    note: string;
    updatedHours?: number;
  }
): Promise<ScanDataDiscrepancy> {
  const response = await apiClient.post<{
    success: boolean;
    data: ScanDataDiscrepancy;
  }>(`/scan-data/discrepancies/${discrepancyId}/resolve`, {
    resolutionMethod: resolutionData.method,
    resolutionNote: resolutionData.note,
    updatedHours: resolutionData.updatedHours,
  });
  return response.data.data;
}

/**
 * Get late records with filtering
 */
export async function getLateRecords(
  filter?: LateRecordFilter,
  page: number = 1,
  pageSize: number = 50
): Promise<{
  data: LateRecord[];
  total: number;
  page: number;
  pageSize: number;
}> {
  const params = new URLSearchParams();
  params.append('page', String(page));
  params.append('pageSize', String(pageSize));

  if (filter) {
    if (filter.projectLocationId)
      params.append('projectLocationId', filter.projectLocationId);
    if (filter.dailyContractorId)
      params.append('dailyContractorId', filter.dailyContractorId);
    if (filter.employeeNumber) params.append('employeeNumber', filter.employeeNumber);
    if (filter.startDate)
      params.append('startDate', filter.startDate.toISOString());
    if (filter.endDate) params.append('endDate', filter.endDate.toISOString());
    if (filter.wagePeriodId) params.append('wagePeriodId', filter.wagePeriodId);
    if (filter.includedInWageCalculation !== undefined)
      params.append(
        'includedInWageCalculation',
        String(filter.includedInWageCalculation)
      );
  }

  const response = await apiClient.get<{
    success: boolean;
    data: LateRecord[];
    pagination: { total: number; page: number; pageSize: number };
  }>(`/late-records?${params.toString()}`);

  return {
    data: response.data.data,
    total: response.data.pagination.total,
    page: response.data.pagination.page,
    pageSize: response.data.pagination.pageSize,
  };
}

/**
 * Trigger discrepancy detection for a date range
 */
export async function triggerDiscrepancyDetection(
  projectLocationId: string,
  startDate: Date,
  endDate: Date
): Promise<{
  detectCounted: number;
  discrepanciesCreated: number;
}> {
  const response = await apiClient.post<{
    success: boolean;
    data: { detected: number; discrepanciesCreated: number };
  }>('/scan-data/detect-discrepancies', {
    projectLocationId,
    startDate: startDate.toISOString(),
    endDate: endDate.toISOString(),
  });

  return {
    detectCounted: response.data.data.detected,
    discrepanciesCreated: response.data.data.discrepanciesCreated,
  };
}
