#!/usr/bin/env python3
"""
capture_manual.py — Auto-generated by doc_builder skill
Run: python scripts/capture_manual.py --base-url http://localhost:3000 --out frontend/public/doc/manual/assets
"""
import argparse
import asyncio
from pathlib import Path
from playwright.async_api import async_playwright

BASE_URL = "http://localhost:3000"
OUT_DIR = Path("frontend/public/doc/manual/assets")

# Credentials for roles found in Production Firestore
CREDENTIALS = {
    "admin":   {"username": "admin",    "password": "admin1"},
    "foreman": {"username": "thiti.m",  "password": "101527"},
    "leader":  {"username": "testld",   "password": "123456"}
}

# Capture targets
# file: filename to save in assets
# path: url path
# role: credentials to use (or none for public)
# wait_selector: selector to wait for before screenshot
CAPTURES = [
    # Public
    {"file": "login_page.png", "path": "/login", "role": None, "wait_selector": "input[name='username']"},
    
    # Foreman (FM)
    {"file": "foreman_reports_list.png", "path": "/daily-reports", "role": "foreman", "wait_selector": "main, #__next"},
    
    # Leader (LD)
    {"file": "leader_workspace.png", "path": "/workspace", "role": "leader", "wait_selector": "main, #__next"},
    {"file": "leader_overtime.png", "path": "/overtime", "role": "leader", "wait_selector": "main, #__next"},
    
    # Admin (AM)
    {"file": "admin_workspace.png", "path": "/workspace", "role": "admin", "wait_selector": "main, #__next"},
    {"file": "admin_project_management.png", "path": "/project-management", "role": "admin", "wait_selector": "main, #__next"},
    {"file": "admin_member_management.png", "path": "/member-management", "role": "admin", "wait_selector": "main, #__next"},
    {"file": "admin_wage_calculation.png", "path": "/wage-calculation", "role": "admin", "wait_selector": "main, #__next"}
]

async def login(page, role: str, base_url: str):
    creds = CREDENTIALS.get(role)
    if not creds:
        return False
    
    print(f"Logging in as {role} ({creds['username']})...")
    try:
        await page.goto(f"{base_url}/login")
        await page.wait_for_selector("input[name='username']", timeout=5000)
        await page.fill("input[name='username']", creds["username"])
        await page.fill("input[name='password']", creds["password"])
        await page.click("button[type='submit']")
        
        # Wait until redirected away from login page
        await page.wait_for_function("() => !window.location.pathname.includes('/login')", timeout=8000)
        await page.wait_for_load_state("load")
        print("Login success!")
        return True
    except Exception as e:
        print(f"Login failed for {role}: {e}")
        return False

def setup_listeners(page):
    page.on("console", lambda msg: print(f"  [BROWSER CONSOLE] {msg.type}: {msg.text}") if msg.type in ("error", "warning") or "error" in msg.text.lower() or "fail" in msg.text.lower() else None)
    page.on("pageerror", lambda err: print(f"  [BROWSER ERROR] {err}"))

async def capture_all(base_url: str, out_dir: Path):
    out_dir.mkdir(parents=True, exist_ok=True)
    async with async_playwright() as pw:
        # Launch browser in headless mode
        browser = await pw.chromium.launch(headless=True)
        current_role = "none"
        context = await browser.new_context(viewport={"width": 1280, "height": 800})
        page = await context.new_page()
        setup_listeners(page)

        for cap in CAPTURES:
            target_role = cap["role"]
            
            # Perform login if role changes
            if target_role != current_role:
                if target_role is not None:
                    # Create a fresh context to clear session storage/cookies
                    await context.close()
                    context = await browser.new_context(viewport={"width": 1280, "height": 800})
                    page = await context.new_page()
                    setup_listeners(page)
                    success = await login(page, target_role, base_url)
                    if not success:
                        print(f"Skipping capture {cap['file']} due to login failure.")
                        current_role = "failed"
                        continue
                    current_role = target_role
                else:
                    await context.close()
                    context = await browser.new_context(viewport={"width": 1280, "height": 800})
                    page = await context.new_page()
                    setup_listeners(page)
                    current_role = None

            url = f"{base_url}{cap['path']}"
            print(f"Navigating to {url}...")
            try:
                print("  [DEBUG] Calling page.goto...")
                await page.goto(url)
                print("  [DEBUG] page.goto completed. Waiting for load state...")
                await page.wait_for_load_state("load")
                print("  [DEBUG] load state complete.")
                if cap.get("wait_selector"):
                    try:
                        print(f"  [DEBUG] Waiting for selector: {cap['wait_selector']}...")
                        await page.wait_for_selector(cap["wait_selector"], timeout=5000)
                        print("  [DEBUG] selector found.")
                    except Exception as e:
                        print(f"  [DEBUG] Selector wait timed out/failed: {e}")
                
                # Extra brief wait for animations/loading states to clear
                print("  [DEBUG] Waiting 1500ms timeout...")
                await page.wait_for_timeout(1500)
                print("  [DEBUG] Taking screenshot...")
                
                out_path = out_dir / cap["file"]
                await page.screenshot(path=str(out_path), full_page=False)
                print(f"  OK: Saved {cap['file']} to {out_path}")
            except Exception as e:
                print(f"  ERROR: Failed to capture {cap['file']}: {e}")

        await context.close()
        await browser.close()

if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--base-url", default=BASE_URL)
    parser.add_argument("--out", default=str(OUT_DIR))
    args = parser.parse_args()
    
    print(f"Starting screenshot capture to {args.out} using base URL {args.base_url}...")
    asyncio.run(capture_all(args.base_url, Path(args.out)))
    print("Capture complete!")
