"use strict";
/**
 * AUTO-SYNCED — DO NOT EDIT THIS FILE DIRECTLY.
 * Source of truth: backend/src/services/reconciliation/segmentEngine.ts
 * Regenerated by scripts/sync-segment-engine.js (runs automatically as
 * `functions`'s `prebuild` step — see functions/package.json).
 */
/**
 * segmentEngine
 *
 * Single source of truth for turning a Daily Report's shift times + scan punches
 * into a reconciliation status (MATCHED / CONFLICTED / MISSING_SCAN / ...).
 *
 * This module is framework-free on purpose (no Firestore, no Express) so it can
 * be shared between the Express backend (`ReconciliationService`) and the Firebase
 * Cloud Function (`functions/src/index.ts`) without either one depending on the
 * other's package. `functions/` gets its copy via `scripts/sync-segment-engine.js`
 * (run as a `prebuild` step) — this file is the ONLY place to hand-edit the logic.
 *
 * Layout:
 *  - buildSegmentsFromShiftTimes: turns the fixed 4-key shiftTimes (day/otMorning/
 *    otNoon/otEvening) into a generic Segment[]. Future formats (e.g. an arbitrary
 *    list of job blocks) get their own `buildSegmentsFrom...` function that
 *    produces the same Segment[] shape — matchSegmentsToPunches does not need to
 *    change to support them.
 *  - matchSegmentsToPunches: pairs scan punches to an arbitrary-length Segment[].
 *    Works with any number of segments; the OT-specific bypass/penalty rules only
 *    fire for segments literally typed 'otMorning'/'otEvening' and are a no-op for
 *    any other segment type.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.punchToMinutes = punchToMinutes;
exports.parseTimeRange = parseTimeRange;
exports.buildSegmentsFromShiftTimes = buildSegmentsFromShiftTimes;
exports.buildSegmentsFromJobSegments = buildSegmentsFromJobSegments;
exports.mergeContiguousSegments = mergeContiguousSegments;
exports.matchSegmentsToPunches = matchSegmentsToPunches;
exports.classifyBySegments = classifyBySegments;
exports.classifyByPunchCoverage = classifyByPunchCoverage;
exports.buildDisplaySegments = buildDisplaySegments;
exports.buildSegmentSnapshots = buildSegmentSnapshots;
// ---------------------------------------------------------------------------
// Time helpers
// ---------------------------------------------------------------------------
/** แปลง HH:mm เป็นจำนวนนาทีจากเที่ยงคืน */
function punchToMinutes(punch) {
    const [h, m] = punch.split(':').map(Number);
    return (h || 0) * 60 + (m || 0);
}
function parseTimeRange(timeStr) {
    if (!timeStr)
        return null;
    const parts = timeStr.split('-').map((s) => s.trim());
    if (parts.length !== 2)
        return null;
    return { start: punchToMinutes(parts[0]), end: punchToMinutes(parts[1]) };
}
function formatTime(mins) {
    const h = Math.floor(mins / 60).toString().padStart(2, '0');
    const m = (mins % 60).toString().padStart(2, '0');
    return `${h}:${m}`;
}
// ---------------------------------------------------------------------------
// Segment builder — fixed 4-key shiftTimes (Daily Report's current format)
// ---------------------------------------------------------------------------
/**
 * ใช้ shiftTimes เป็น source of truth ในการสร้างช่วงเวลาที่ควรจะมีการสแกน
 * คืน null ถ้าไม่มี shiftTimes.day (แปลว่า Daily Report ไม่มีข้อมูลช่วงเวลาทำงาน)
 *
 * ⚠️ hasOtNoon ต้องมาจาก shiftTimes.otNoon เท่านั้น ห้ามผสมค่าที่คำนวณจาก scan
 * (timesheetOtNoon ฯลฯ) เพราะ segment ต้องสร้างจาก daily report เท่านั้น — ดู
 * docs/work-hour-monitoring-logic.md section 11, Bug #3
 */
function buildSegmentsFromShiftTimes(shiftTimes) {
    const dayShift = parseTimeRange(shiftTimes?.day);
    if (!dayShift)
        return null;
    const otMorning = parseTimeRange(shiftTimes?.otMorning);
    const otNoon = parseTimeRange(shiftTimes?.otNoon);
    const otEvening = parseTimeRange(shiftTimes?.otEvening);
    const segments = [];
    if (otMorning) {
        segments.push({ start: otMorning.start, end: otMorning.end, type: 'otMorning' });
    }
    const hasOtNoon = !!otNoon;
    const hasOtEveningConnected = !!otEvening && otEvening.start === dayShift.end;
    if (hasOtNoon) {
        segments.push({ start: dayShift.start, end: dayShift.end, type: 'normal' });
    }
    else if (dayShift.end <= 12 * 60) {
        segments.push({ start: dayShift.start, end: dayShift.end, type: 'morning' });
    }
    else if (dayShift.start >= 13 * 60) {
        if (hasOtEveningConnected) {
            segments.push({ start: dayShift.start, end: otEvening.end, type: 'combined_afternoon_evening' });
        }
        else {
            segments.push({ start: dayShift.start, end: dayShift.end, type: 'afternoon' });
        }
    }
    else {
        segments.push({ start: dayShift.start, end: 12 * 60, type: 'morning' });
        if (hasOtEveningConnected) {
            segments.push({ start: 13 * 60, end: otEvening.end, type: 'combined_afternoon_evening' });
        }
        else {
            segments.push({ start: 13 * 60, end: dayShift.end, type: 'afternoon' });
        }
    }
    if (otEvening && !(hasOtEveningConnected && !hasOtNoon)) {
        segments.push({ start: otEvening.start, end: otEvening.end, type: 'otEvening' });
    }
    return segments;
}
/**
 * แปลง jobSegments (N งานย่อยต่อวัน) เป็น Segment[] เดียวกัน — เรียกใช้
 * buildSegmentsFromShiftTimes ซ้ำต่อ 1 งาน (ตัวมันเองต่องานยังเป็น shiftTimes
 * แบบ 4-key เดิม แค่ scope แคบลงมาระดับ "งาน" แทน "วัน") แล้วต่อผลของทุกงาน
 * เรียงตามเวลาเริ่มให้ matchSegmentsToPunches ใช้ต่อได้ทันที (ตัว matcher เอง
 * ไม่ต้องแก้อะไรเลย — นี่คือประโยชน์ของการแยก builder/matcher ไว้ตั้งแต่ Track A)
 */
function buildSegmentsFromJobSegments(jobSegments) {
    if (!jobSegments)
        return [];
    const result = [];
    for (const [jobKey, job] of Object.entries(jobSegments)) {
        const jobBaseSegments = buildSegmentsFromShiftTimes(job.shiftTimes);
        if (!jobBaseSegments)
            continue;
        for (const seg of jobBaseSegments) {
            result.push({
                ...seg,
                jobKey,
                taskId: job.taskId,
                taskName: job.taskName,
                subtaskId: job.subtaskId,
                subtaskName: job.subtaskName,
                location: job.location,
                progressPhotos: job.photos?.regular,
            });
        }
    }
    return result.sort((a, b) => a.start - b.start);
}
/**
 * รวม segment ที่ต่อกันพอดี (end ของอันก่อน === start ของอันถัดไป) เป็นก้อนเดียว
 * — ใช้ตอนมี jobSegments หลายงานในวันเดียว เพื่อไม่ให้จุดที่ "สลับงาน" (เช่น งาน A
 * จบ 10:00 งาน B เริ่ม 10:00 พอดี) ถูกตีความว่าเป็นจุดที่ต้องมีสแกนนิ้ว — คนงานสลับ
 * งานระหว่างวันโดยไม่ได้ออกจากไซต์ เครื่องสแกนนิ้วจับได้แค่เข้า-ออกไซต์จริงเท่านั้น
 *
 * รวมแล้วช่องว่างที่เหลืออยู่ (เช่น พักเที่ยง หรือช่วงที่ไม่มีงานระบุเลย) จะยังเป็น
 * ขอบเขตที่ต้องมีสแกนอยู่เหมือนเดิม — ฟังก์ชันนี้ลบแค่ "รอยต่อปลอม" ระหว่างงานที่ทำ
 * ต่อเนื่องกันจริงๆ ไม่ได้ลบข้อกำหนดการสแกนช่วงพักที่มีอยู่แล้ว
 */
function mergeContiguousSegments(segments) {
    if (segments.length === 0)
        return [];
    const sorted = [...segments].sort((a, b) => a.start - b.start);
    const merged = [{ ...sorted[0] }];
    for (let i = 1; i < sorted.length; i++) {
        const last = merged[merged.length - 1];
        const seg = sorted[i];
        if (seg.start === last.end) {
            last.end = seg.end;
        }
        else {
            merged.push({ ...seg });
        }
    }
    return merged;
}
/**
 * จับคู่ scanPunches กับ segments ทีละตัว (เรียงตามลำดับที่ส่งมาใน `segments`).
 * แต่ละ punch ถูกใช้ได้ครั้งเดียว (usedPunches) ยกเว้น punch ที่ตรงกับรอยต่อพอดี
 * ระหว่าง 2 segments ติดกัน (isBoundaryShared) ซึ่งใช้เป็นทั้ง OUT ของตัวก่อน
 * และ IN ของตัวถัดไปได้
 *
 * หมายเหตุ: `segments` ต้องเรียงจากเวลาเริ่มน้อยไปมากอยู่แล้วก่อนเรียกฟังก์ชันนี้
 * (buildSegmentsFromShiftTimes คืนมาเรียงอยู่แล้ว — builder อื่นในอนาคตต้อง sort เอง)
 */
function matchSegmentsToPunches(segments, scanPunches) {
    const sortedScans = scanPunches.map((p) => punchToMinutes(p)).sort((a, b) => a - b);
    const otMorningSeg = segments.find((s) => s.type === 'otMorning') ?? null;
    let isConflicted = false;
    let totalLateMinutes = 0;
    let totalEarlyLeaveMinutes = 0;
    let penaltyOtMorning = 0;
    let penaltyOtEvening = 0;
    const conflictNotes = [];
    const usedPunches = new Set();
    const perSegment = [];
    for (let segIndex = 0; segIndex < segments.length; segIndex++) {
        const seg = segments[segIndex];
        const nextSeg = segments[segIndex + 1];
        const available = sortedScans.filter((t) => !usedPunches.has(t));
        let closestIn = -1;
        let minInDiff = Infinity;
        for (const t of available) {
            if (t > seg.end)
                continue;
            const diff = Math.abs(t - seg.start);
            if (diff < minInDiff) {
                minInDiff = diff;
                closestIn = t;
            }
            else if (diff === minInDiff && t < closestIn) {
                closestIn = t;
            }
        }
        let closestOut = -1;
        let minOutDiff = Infinity;
        for (const t of available) {
            if (t <= closestIn)
                continue;
            const diff = Math.abs(t - seg.end);
            if (diff < minOutDiff) {
                minOutDiff = diff;
                closestOut = t;
            }
            else if (diff === minOutDiff && t > closestOut) {
                closestOut = t;
            }
        }
        if (closestIn !== -1)
            usedPunches.add(closestIn);
        // Allow boundary-shared punches to be reused as IN of the next segment
        if (closestOut !== -1) {
            const isBoundaryShared = nextSeg && seg.end === nextSeg.start;
            if (!isBoundaryShared) {
                usedPunches.add(closestOut);
            }
        }
        let late = 0;
        let early = 0;
        // ── Transition scan bypass rules (OT เช้า ↔ กะปกติ) ──
        const isMorningTransition = seg.start === 480 && !!otMorningSeg; // กะเช้าปกติที่ทำ OT ต่อเนื่อง
        const isOtMorningTransition = seg.type === 'otMorning' && !!nextSeg && seg.end === nextSeg.start; // กะ OT เช้าที่ทำเชื่อมต่อกะปกติ
        if (closestIn === -1 || minInDiff > 90) {
            const prevHasIn = isMorningTransition &&
                !!otMorningSeg &&
                sortedScans.some((t) => t <= 480 + 90 && t >= otMorningSeg.start - 90);
            if (!isMorningTransition || !prevHasIn) {
                isConflicted = true;
                const reason = `ไม่พบสแกน IN สำหรับ segment ${formatTime(seg.start)}–${formatTime(seg.end)}`;
                conflictNotes.push(reason);
                perSegment.push({
                    segment: seg,
                    matchedInMinutes: null,
                    matchedOutMinutes: closestOut !== -1 ? closestOut : null,
                    lateMinutes: 0,
                    earlyLeaveMinutes: 0,
                    conflicted: true,
                    conflictReason: reason,
                });
                continue;
            }
        }
        else {
            const rawLate = closestIn - seg.start;
            if (isMorningTransition && rawLate <= 5) {
                late = 0;
            }
            else {
                late = Math.max(0, rawLate);
            }
        }
        if (closestOut === -1 || minOutDiff > 90) {
            const nextHasOut = isOtMorningTransition && !!nextSeg && sortedScans.some((t) => t >= seg.end - 90 && t <= nextSeg.end + 90);
            if (!isOtMorningTransition || !nextHasOut) {
                isConflicted = true;
                const reason = `ไม่พบสแกน OUT สำหรับ segment ${formatTime(seg.start)}–${formatTime(seg.end)}`;
                conflictNotes.push(reason);
                perSegment.push({
                    segment: seg,
                    matchedInMinutes: closestIn !== -1 ? closestIn : null,
                    matchedOutMinutes: null,
                    lateMinutes: late,
                    earlyLeaveMinutes: 0,
                    conflicted: true,
                    conflictReason: reason,
                });
                continue;
            }
        }
        else {
            early = Math.max(0, seg.end - closestOut);
        }
        let segConflicted = false;
        let segReason;
        if (late > 30) {
            isConflicted = true;
            segConflicted = true;
            segReason = `สแกนเข้าสายเกิน 30 นาทีในรอบ ${formatTime(seg.start)} (${late} นาที)`;
            conflictNotes.push(segReason);
        }
        if (early > 30) {
            isConflicted = true;
            segConflicted = true;
            segReason = `สแกนออกก่อนเกิน 30 นาทีในรอบ ${formatTime(seg.end)} (${early} นาที)`;
            conflictNotes.push(segReason);
        }
        if (late > 0) {
            totalLateMinutes += late;
            if (seg.type === 'otMorning' || (otMorningSeg && seg.start === otMorningSeg.start)) {
                penaltyOtMorning += late;
            }
        }
        if (early > 0) {
            totalEarlyLeaveMinutes += early;
            if (seg.type === 'otEvening' || seg.type === 'combined_afternoon_evening') {
                penaltyOtEvening += early;
            }
        }
        perSegment.push({
            segment: seg,
            matchedInMinutes: closestIn !== -1 ? closestIn : null,
            matchedOutMinutes: closestOut !== -1 ? closestOut : null,
            lateMinutes: late,
            earlyLeaveMinutes: early,
            conflicted: segConflicted,
            conflictReason: segReason,
        });
    }
    const consumedMinutes = new Set();
    perSegment.forEach((m) => {
        if (m.matchedInMinutes != null)
            consumedMinutes.add(m.matchedInMinutes);
        if (m.matchedOutMinutes != null)
            consumedMinutes.add(m.matchedOutMinutes);
    });
    const extraPunches = sortedScans.filter((t) => !consumedMinutes.has(t));
    return {
        perSegment,
        isConflicted,
        conflictNote: conflictNotes.join(', '),
        totalLateMinutes,
        totalEarlyLeaveMinutes,
        penaltyOtMorning,
        penaltyOtEvening,
        extraPunches,
    };
}
function classifyBaseCases(params) {
    const { scanCount, dailyWorkExists, isHoliday, isLeave, leaveHours, dailyReportHours, firstScanPunch } = params;
    const isFullDayLeave = isLeave === true && (leaveHours ?? 0) >= 8;
    const isPartialLeave = isLeave === true && (leaveHours ?? 0) > 0 && (leaveHours ?? 0) < 8;
    const noWorkHours = !dailyReportHours || dailyReportHours === 0;
    const dailyExists = dailyWorkExists || isPartialLeave;
    if (isFullDayLeave && noWorkHours) {
        return { status: 'LEAVE' };
    }
    if (isHoliday && noWorkHours) {
        if (scanCount > 0) {
            return { status: 'CONFLICTED', suggestedHours: 0, note: `วันหยุดแต่พบข้อมูลการสแกนนิ้ว (${scanCount} ครั้ง)` };
        }
        return { status: 'HOLIDAY' };
    }
    if (isPartialLeave && !dailyWorkExists) {
        if (scanCount > 0) {
            return {
                status: 'CONFLICTED',
                suggestedHours: 0,
                note: `แจ้งลา ${leaveHours} ชม. แต่ใน Daily Report ไม่มีการลงเวลาทำงานส่วนที่เหลือ และพบข้อมูลสแกนนิ้ว (${scanCount} ครั้ง)`,
            };
        }
        return {
            status: 'MISSING_DAILY',
            suggestedHours: 0,
            note: `แจ้งลา ${leaveHours} ชม. แต่ใน Daily Report ไม่มีการลงเวลาทำงานส่วนที่เหลือ`,
        };
    }
    if (!dailyExists && scanCount === 0)
        return { status: 'ABSENT' };
    if (!dailyExists && scanCount > 0)
        return { status: 'MISSING_DAILY' };
    if (dailyExists && scanCount === 0) {
        return { status: 'MISSING_SCAN', suggestedHours: 0, note: 'ไม่พบข้อมูลการสแกนนิ้ว' };
    }
    if (dailyExists && scanCount === 1) {
        return {
            status: 'CONFLICTED',
            suggestedHours: 0,
            note: `ข้อมูลสแกนนิ้วไม่เพียงพอ (พบเพียงครั้งเดียว: ${firstScanPunch}) — Admin ต้องเติมเวลาที่ขาด`,
        };
    }
    return null; // no base case matched — proceed to segment/coverage check
}
// ---------------------------------------------------------------------------
// [PRIMARY] classifyBySegments
// ---------------------------------------------------------------------------
function classifyBySegments(params) {
    const { shiftTimes, jobSegments, scanPunches, timesheetNormalHours, timesheetOtMorning, timesheetOtNoon, timesheetOtEvening, dailyReportHours, isHoliday, isLeave, leaveHours, } = params;
    const hasJobSegments = !!jobSegments && Object.keys(jobSegments).length > 0;
    const scanCount = (scanPunches || []).length;
    const dailyWorkExists = hasJobSegments || !!shiftTimes?.day || (dailyReportHours !== undefined && dailyReportHours > 0);
    const base = classifyBaseCases({
        scanCount,
        dailyWorkExists,
        dailyReportHours,
        isHoliday,
        isLeave,
        leaveHours,
        firstScanPunch: scanPunches?.[0],
    });
    if (base)
        return base;
    // jobSegments (N งานย่อยต่อวัน) คือ source of truth เมื่อมีค่า — ดู doc comment
    // ของ JobSegmentEntry ด้านบน ยืนยันกับ After-Sale แล้วว่า shiftTimes เดิม
    // เป็นแค่ของสรุปแบบตัดทอน ไม่ใช้ตัดสิน MATCHED/CONFLICTED อีกต่อไปเมื่อมี jobSegments
    let segments;
    if (hasJobSegments) {
        const rawJobSegments = buildSegmentsFromJobSegments(jobSegments);
        if (rawJobSegments.length === 0) {
            return { status: 'MISSING_DAILY', note: 'Daily Report ไม่มีข้อมูลช่วงเวลาทำงาน (Shift Times)' };
        }
        // งานที่ต่อกันพอดี (สลับงานโดยไม่ออกจากไซต์) ต้องรวมเป็น segment เดียวก่อนจับคู่
        // สแกน ไม่งั้นตัว matcher จะไปคาดหวังสแกนนิ้วตรงจุดสลับงานทั้งที่ไม่มีจริง
        segments = mergeContiguousSegments(rawJobSegments);
    }
    else {
        if (!shiftTimes || !shiftTimes.day) {
            return { status: 'MISSING_DAILY', note: 'Daily Report ไม่มีข้อมูลช่วงเวลาทำงาน (Shift Times)' };
        }
        segments = buildSegmentsFromShiftTimes(shiftTimes);
        if (!segments) {
            return { status: 'MISSING_DAILY', note: 'Daily Report ไม่มีข้อมูลช่วงเวลาทำงาน (Shift Times)' };
        }
    }
    const outcome = matchSegmentsToPunches(segments, scanPunches);
    // สแกนที่เหลือไม่ตรงกับ segment ไหนเลย (เช่น สแกนหลังเวลาที่ Daily Report บอกว่าเลิกงาน) —
    // เป็นสัญญาณว่ามีเวลาทำงานที่ยังไม่ถูกบันทึกไว้ ต้องบังคับ CONFLICTED เสมอ ไม่ว่า segment
    // ที่ประกาศไว้จะตรงครบแค่ไหนก็ตาม ไม่งั้นสแกนส่วนเกินนี้จะถูกมองข้ามไปเงียบๆ (พบจากรีวิวจริงกับผู้ใช้)
    const extraNote = outcome.extraPunches.length > 0
        ? `พบสแกน ${outcome.extraPunches.map(formatTime).join(', ')} ที่ไม่ตรงช่วงเวลาใด`
        : null;
    // Daily Report ที่ประกาศช่วงเวลาทำงาน "ปกติ" (ไม่นับ otMorning/otEvening ซึ่งเป็นส่วนเสริม)
    // สั้นกว่า 1 วันมาตรฐาน (08:00-17:00) โดยไม่มีใบลา/วันหยุดมารองรับส่วนที่ขาด — ต้องบังคับ
    // CONFLICTED เสมอเช่นกัน เพราะไม่รู้ว่าลืมลงข้อมูล (report/สแกน) หรือลาแล้วลืมลงใบลา หรือ
    // ตั้งใจให้สั้นจริงๆ ปล่อยให้ admin เป็นคนตัดสินใจแทนที่จะปล่อยผ่านเป็น MATCHED เงียบๆ
    const NORMAL_DAY_START = 8 * 60; // 08:00
    const NORMAL_DAY_END = 17 * 60; // 17:00
    const coverageSegments = segments.filter((s) => s.type !== 'otMorning' && s.type !== 'otEvening');
    const coverageStart = coverageSegments.length > 0 ? Math.min(...coverageSegments.map((s) => s.start)) : null;
    const coverageEnd = coverageSegments.length > 0 ? Math.max(...coverageSegments.map((s) => s.end)) : null;
    const isShortDay = !isLeave &&
        !isHoliday &&
        coverageStart !== null &&
        coverageEnd !== null &&
        (coverageStart > NORMAL_DAY_START || coverageEnd < NORMAL_DAY_END);
    const shortDayNote = isShortDay
        ? `Daily Report ลงเวลาแค่ ${formatTime(coverageStart)}-${formatTime(coverageEnd)} ไม่ครบวันทำงานมาตรฐาน (08:00-17:00) และไม่มีใบลา/วันหยุดรองรับ`
        : null;
    if (outcome.isConflicted || extraNote || shortDayNote) {
        return {
            status: 'CONFLICTED',
            suggestedHours: dailyReportHours,
            approvedNormalHours: timesheetNormalHours,
            approvedOtMorning: timesheetOtMorning,
            approvedOtNoon: timesheetOtNoon,
            approvedOtEvening: timesheetOtEvening,
            totalApprovedHours: (timesheetNormalHours || 0) + (timesheetOtMorning || 0) + (timesheetOtNoon || 0) + (timesheetOtEvening || 0),
            approvalSource: 'daily_report',
            lateMinutes: outcome.totalLateMinutes,
            earlyLeaveMinutes: outcome.totalEarlyLeaveMinutes,
            isLate: outcome.totalLateMinutes > 0,
            isEarlyLeave: outcome.totalEarlyLeaveMinutes > 0,
            note: [outcome.conflictNote, extraNote, shortDayNote].filter(Boolean).join(' · ') || null,
        };
    }
    let approvedNormal = timesheetNormalHours ?? dailyReportHours ?? 0;
    let approvedMorning = timesheetOtMorning ?? 0;
    let approvedNoon = timesheetOtNoon ?? 0;
    let approvedEvening = timesheetOtEvening ?? 0;
    let autoNote = '';
    if (outcome.penaltyOtMorning > 0 && approvedMorning > 0) {
        const penaltyMins = Math.ceil(outcome.penaltyOtMorning / 30) * 30;
        approvedMorning = Math.max(0, approvedMorning - penaltyMins / 60);
        autoNote += `สายช่วง OT เช้า ${outcome.penaltyOtMorning} นาที (หัก ${penaltyMins} นาที) `;
    }
    if (outcome.penaltyOtEvening > 0 && approvedEvening > 0) {
        const penaltyMins = Math.ceil(outcome.penaltyOtEvening / 30) * 30;
        approvedEvening = Math.max(0, approvedEvening - penaltyMins / 60);
        autoNote += `ออกก่อนช่วง OT เย็น ${outcome.penaltyOtEvening} นาที (หัก ${penaltyMins} นาที) `;
    }
    return {
        status: 'MATCHED',
        suggestedHours: dailyReportHours,
        approvedNormalHours: approvedNormal,
        approvedOtMorning: approvedMorning,
        approvedOtNoon: approvedNoon,
        approvedOtEvening: approvedEvening,
        totalApprovedHours: approvedNormal + approvedMorning + approvedNoon + approvedEvening,
        approvalSource: 'daily_report',
        lateMinutes: outcome.totalLateMinutes,
        earlyLeaveMinutes: outcome.totalEarlyLeaveMinutes,
        isLate: outcome.totalLateMinutes > 0,
        isEarlyLeave: outcome.totalEarlyLeaveMinutes > 0,
        note: autoNote || null,
    };
}
// ---------------------------------------------------------------------------
// [PRIMARY] classifyByPunchCoverage — legacy fallback for docs without shiftTimes
// ---------------------------------------------------------------------------
function classifyByPunchCoverage(params) {
    const { dailyReportPunches, scanPunches, timesheetNormalHours, timesheetOtMorning, timesheetOtNoon, timesheetOtEvening, dailyReportHours, isHoliday, isLeave, leaveHours, } = params;
    const dailyPunchesValid = Array.isArray(dailyReportPunches) && dailyReportPunches.length >= 2;
    const scanCount = (scanPunches || []).length;
    const scanValid = scanCount >= 2;
    const dailyWorkExists = dailyPunchesValid || (dailyReportHours !== undefined && dailyReportHours > 0);
    const isFullDayLeave = isLeave === true && (leaveHours ?? 0) >= 8;
    const isPartialLeave = isLeave === true && (leaveHours ?? 0) > 0 && (leaveHours ?? 0) < 8;
    const noWorkHours = !dailyReportHours || dailyReportHours === 0;
    const dailyExists = dailyWorkExists || isPartialLeave;
    if (isFullDayLeave && noWorkHours)
        return { status: 'LEAVE' };
    if (isHoliday && noWorkHours) {
        if (scanCount > 0) {
            return { status: 'CONFLICTED', suggestedHours: 0, note: `วันหยุดแต่พบข้อมูลการสแกนนิ้ว (${scanCount} ครั้ง)` };
        }
        return { status: 'HOLIDAY' };
    }
    if (isPartialLeave && !dailyWorkExists) {
        if (scanCount > 0) {
            return {
                status: 'CONFLICTED',
                suggestedHours: 0,
                note: `แจ้งลา ${leaveHours} ชม. แต่ใน Daily Report ไม่มีการลงเวลาทำงานส่วนที่เหลือ และพบข้อมูลสแกนนิ้ว (${scanCount} ครั้ง)`,
            };
        }
        return {
            status: 'MISSING_DAILY',
            suggestedHours: 0,
            note: `แจ้งลา ${leaveHours} ชม. แต่ใน Daily Report ไม่มีการลงเวลาทำงานส่วนที่เหลือ`,
        };
    }
    if (!dailyExists && !scanValid)
        return { status: 'ABSENT' };
    if (!dailyExists && scanValid)
        return { status: 'MISSING_DAILY' };
    if (dailyExists && !scanValid) {
        if (scanCount === 0) {
            return { status: 'MISSING_SCAN', suggestedHours: 0, note: 'ไม่พบข้อมูลการสแกนนิ้ว' };
        }
        return {
            status: 'CONFLICTED',
            suggestedHours: 0,
            note: `ข้อมูลสแกนนิ้วไม่เพียงพอ (พบเพียงครั้งเดียว: ${scanPunches[0]}) — Admin ต้องเติมเวลาที่ขาด`,
        };
    }
    if (!dailyPunchesValid) {
        return { status: 'MISSING_DAILY', note: 'Daily Report ไม่มีข้อมูลช่วงเวลาทำงาน (Shift Times)' };
    }
    const sortedReportPunches = [...dailyReportPunches].sort();
    const reportStart = punchToMinutes(sortedReportPunches[0]);
    const reportEnd = punchToMinutes(sortedReportPunches[sortedReportPunches.length - 1]);
    const sortedScan = [...(scanPunches || [])].sort();
    const scanFirstIn = punchToMinutes(sortedScan[0]);
    const scanLastOut = punchToMinutes(sortedScan[sortedScan.length - 1]);
    const lateMinutes = Math.max(0, scanFirstIn - reportStart);
    const earlyLeaveMinutes = Math.max(0, reportEnd - scanLastOut);
    const CONFLICT_THRESHOLD = 30;
    const isLateConflict = lateMinutes > CONFLICT_THRESHOLD;
    const isEarlyLeaveConflict = earlyLeaveMinutes > CONFLICT_THRESHOLD;
    if (isLateConflict || isEarlyLeaveConflict) {
        return {
            status: 'CONFLICTED',
            lateMinutes,
            earlyLeaveMinutes,
            isLate: isLateConflict,
            isEarlyLeave: isEarlyLeaveConflict,
            note: isEarlyLeaveConflict
                ? `ออกก่อนเกิน ${CONFLICT_THRESHOLD} นาที (${earlyLeaveMinutes} นาที) — ต้องตรวจสอบ Daily Report`
                : `สายเกิน ${CONFLICT_THRESHOLD} นาที (${lateMinutes} นาที) — ต้องตรวจสอบ Daily Report`,
        };
    }
    let approvedNormalHours = timesheetNormalHours ?? dailyReportHours ?? 0;
    let approvedOtMorning = timesheetOtMorning ?? 0;
    let approvedOtNoon = timesheetOtNoon ?? 0;
    let approvedOtEvening = timesheetOtEvening ?? 0;
    let autoNote = '';
    const isLateForOT = lateMinutes > 0 && (timesheetOtMorning ?? 0) > 0;
    const isEarlyLeaveFromOT = earlyLeaveMinutes > 0 && (timesheetOtEvening ?? 0) > 0;
    if (isLateForOT) {
        const penaltyMins = Math.ceil(lateMinutes / 30) * 30;
        approvedOtMorning = Math.max(0, (timesheetOtMorning ?? 0) - penaltyMins / 60);
        autoNote += `สายช่วง OT เช้า ${lateMinutes} นาที (หัก ${penaltyMins} นาที) `;
    }
    if (isEarlyLeaveFromOT) {
        const penaltyMins = Math.ceil(earlyLeaveMinutes / 30) * 30;
        approvedOtEvening = Math.max(0, (timesheetOtEvening ?? 0) - penaltyMins / 60);
        autoNote += `ออกก่อนช่วง OT เย็น ${earlyLeaveMinutes} นาที (หัก ${penaltyMins} นาที) `;
    }
    return {
        status: 'MATCHED',
        suggestedHours: dailyReportHours,
        approvedNormalHours,
        approvedOtMorning,
        approvedOtNoon,
        approvedOtEvening,
        totalApprovedHours: approvedNormalHours + approvedOtMorning + approvedOtNoon + approvedOtEvening,
        approvalSource: 'daily_report',
        lateMinutes,
        earlyLeaveMinutes,
        isLate: lateMinutes > 0,
        isEarlyLeave: earlyLeaveMinutes > 0,
        note: autoNote || null,
    };
}
// ---------------------------------------------------------------------------
// Display segments — for ReconciliationRecord.segments (UI rendering only)
// ---------------------------------------------------------------------------
//
// classifyBySegments() above merges morning+afternoon into ONE 'normal' segment
// when otNoon is present, because for MATCHED/CONFLICTED purposes there is no
// scan expected at the 12:00/13:00 boundary. The UI, however, has always shown
// that case as 3 separate boxes (เช้า / OT เที่ยง / บ่าย) — buildDisplaySegments
// preserves that exact visual behavior while still going through the shared
// matchSegmentsToPunches matcher (no separate matching logic to maintain).
// This is display-only: it does NOT feed into the MATCHED/CONFLICTED decision.
// `any[]` on purpose: leaveEntries shapes vary slightly between call sites
// (CreateReconciliationRecordInput.leaveEntries doesn't even declare timeRange
// in its type even though it's present at runtime) — this reads .timeRange
// defensively and skips anything that doesn't parse, so a loose type here is
// more honest than a strict interface no caller actually satisfies.
function isSegmentCoveredByLeave(leaveEntries, start, end) {
    if (!leaveEntries || leaveEntries.length === 0)
        return false;
    for (const entry of leaveEntries) {
        const range = parseTimeRange(entry?.timeRange);
        if (!range)
            continue;
        const overlapStart = Math.max(start, range.start);
        const overlapEnd = Math.min(end, range.end);
        if (overlapEnd > overlapStart) {
            const overlapDuration = overlapEnd - overlapStart;
            const segmentDuration = end - start;
            if (segmentDuration > 0 && overlapDuration >= segmentDuration * 0.8)
                return true;
        }
    }
    return false;
}
/**
 * เหมือน buildSegmentsFromShiftTimes แต่ "ไม่รวม" เช้า+บ่ายเป็น 1 ก้อนตอนมี OT เที่ยง
 * (ใช้แค่สำหรับแสดงผล UI — ตัดสิน MATCHED/CONFLICTED จริงใช้ buildSegmentsFromShiftTimes)
 */
function buildDisplaySegments(shiftTimes, leaveEntries) {
    const dayShift = parseTimeRange(shiftTimes?.day);
    if (!dayShift)
        return [];
    const otMorning = parseTimeRange(shiftTimes?.otMorning);
    const otNoon = parseTimeRange(shiftTimes?.otNoon);
    const otEvening = parseTimeRange(shiftTimes?.otEvening);
    const morningEnd = Math.min(dayShift.end, 12 * 60);
    const afternoonStart = Math.max(dayShift.start, 13 * 60);
    const isMorningActive = dayShift.start < 13 * 60;
    const isAfternoonActive = dayShift.end > 12 * 60;
    const segments = [];
    if (otMorning)
        segments.push({ start: otMorning.start, end: otMorning.end, type: 'otMorning' });
    if (isMorningActive && !isSegmentCoveredByLeave(leaveEntries, dayShift.start, morningEnd)) {
        segments.push({ start: dayShift.start, end: morningEnd, type: 'morning' });
    }
    if (otNoon)
        segments.push({ start: otNoon.start, end: otNoon.end, type: 'otNoon' });
    if (isAfternoonActive && !isSegmentCoveredByLeave(leaveEntries, afternoonStart, dayShift.end)) {
        segments.push({ start: afternoonStart, end: dayShift.end, type: 'afternoon' });
    }
    if (otEvening)
        segments.push({ start: otEvening.start, end: otEvening.end, type: 'otEvening' });
    return segments.sort((a, b) => a.start - b.start);
}
function extractPhoto(groupData, which) {
    if (!groupData)
        return null;
    if (Array.isArray(groupData)) {
        return which === 'in' ? (groupData[0] ?? null) : (groupData[groupData.length - 1] ?? null);
    }
    if (typeof groupData === 'object') {
        const obj = groupData;
        if (which in obj)
            return obj[which] ?? null;
        const keys = Object.keys(obj);
        const isNumericMap = keys.length > 0 && keys.every((k) => /^\d+$/.test(k));
        if (isNumericMap) {
            const sortedKeys = keys.map(Number).sort((a, b) => a - b);
            const targetKey = which === 'in' ? sortedKeys[0] : sortedKeys[sortedKeys.length - 1];
            return obj[String(targetKey)] ?? null;
        }
    }
    return null;
}
function extractRegularPhoto(regular, index) {
    if (!regular)
        return null;
    if (Array.isArray(regular))
        return regular[index] ?? null;
    if (typeof regular === 'object') {
        const obj = regular;
        return obj[String(index)] ?? null;
    }
    return null;
}
/**
 * ผลลัพธ์สำเร็จรูปสำหรับ UI แสดงตาราง work-hour-monitoring — คำนวณครั้งเดียวที่ backend
 * แล้ว persist ไปกับ ReconciliationRecord.segments เพื่อไม่ให้ frontend ต้องจับคู่ punch เอง
 * (เดิม WorkHourComparisonTable.tsx ทำ matching ของตัวเองอีกรอบ — เป็น engine ที่ 3)
 */
function buildSegmentSnapshots(shiftTimes, scanPunches, photos, leaveEntries) {
    const displaySegments = buildDisplaySegments(shiftTimes, leaveEntries);
    if (displaySegments.length === 0)
        return [];
    const outcome = matchSegmentsToPunches(displaySegments, scanPunches);
    return outcome.perSegment.map((m) => {
        let photoIn = null;
        let photoOut = null;
        if (m.segment.type === 'morning') {
            photoIn = extractRegularPhoto(photos?.regular, 0);
            photoOut = extractRegularPhoto(photos?.regular, 1);
        }
        else if (m.segment.type === 'afternoon') {
            photoIn = extractRegularPhoto(photos?.regular, 2);
            photoOut = extractRegularPhoto(photos?.regular, 3);
        }
        else {
            const group = photos?.[m.segment.type];
            photoIn = extractPhoto(group, 'in');
            photoOut = extractPhoto(group, 'out');
        }
        return {
            type: m.segment.type,
            expectedStart: m.segment.start,
            expectedEnd: m.segment.end,
            matchedInMinutes: m.matchedInMinutes,
            matchedOutMinutes: m.matchedOutMinutes,
            lateMinutes: m.lateMinutes,
            earlyLeaveMinutes: m.earlyLeaveMinutes,
            conflicted: m.conflicted,
            conflictReason: m.conflictReason,
            photoIn,
            photoOut,
        };
    });
}
//# sourceMappingURL=segmentEngine.js.map